# Generated by Django 4.1.8 on 2023-04-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
        ('storerequest', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_status', models.BooleanField(default=True)),
                ('transfer_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storerequest_stocktransfer', to='storerequest.storerequest')),
            ],
        ),
        migrations.CreateModel(
            name='TransferDrug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_drug_quantity', models.IntegerField()),
                ('transfer_drug_status', models.CharField(choices=[('REQ', 'requested'), ('TRA', 'transfer'), ('PUR', 'purchased'), ('CLS', 'closed')], default='REQ', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_transfer_drug', to='drug.drug')),
                ('from_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_stock_from', to='stock.storestock')),
                ('to_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_stock_to', to='stock.storestock')),
                ('transfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_transfer_drug', to='storetransfer.stocktransfer')),
            ],
        ),
    ]
