# Generated by Django 4.1.8 on 2023-04-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDrug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('invoice_quantity', models.IntegerField()),
                ('drug_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugsdetails_drug', to='drug.drug')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drug', to='purchaseorder.purchaseorder')),
            ],
        ),
    ]
