# Generated by Django 4.1.8 on 2023-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasedrug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedrug',
            name='drug_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedrug',
            name='invoice_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedrug',
            name='order_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
