# Generated by Django 4.1.8 on 2023-04-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_dispensing', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='SoldDrug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sold_quantity', models.IntegerField()),
                ('sell_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_drug', to='dispensing.dispensing')),
                ('store_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stock_drug', to='stock.storestock')),
            ],
        ),
    ]
