# Generated by Django 4.1.8 on 2023-05-12 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storerequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdrug',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_requested', to='storerequest.storerequest'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
