# Generated by Django 4.1.8 on 2023-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
                ('store_reg_no', models.CharField(max_length=30)),
                ('store_location', models.CharField(max_length=30)),
                ('store_phone1', models.CharField(max_length=30)),
                ('store_phone2', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
